# Generated by Django 4.2.7 on 2023-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('utilidad', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('oficio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pais_fabricacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('registro_cantidad', models.IntegerField()),
                ('codigo', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroMercadeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entrada', models.IntegerField()),
                ('cantidad_vendida', models.IntegerField()),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_bajo', models.IntegerField()),
                ('fecha_ultima_compra', models.DateField()),
                ('transporte', models.CharField(max_length=100)),
            ],
        ),
    ]
